application: oahu-time
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /favicon\.ico
  static_files: pics/favicon.ico
  upload: pics/favicon\.ico

- url: /files
  static_dir: files

- url: /fonts
  static_dir: fonts

- url: /pics
  static_dir: pics

- url: /.*
  script: oahu-time-server.app
